{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kasechange/1.4.1-wasmjs1/kasechange-1.4.1-wasmjs1.module",
    "group": "net.pearx.kasechange",
    "module": "kasechange",
    "version": "1.4.1-wasmjs1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kasechange-iosSimulatorArm64Main-1.4.1-wasmjs1.klib",
          "url": "kasechange-iossimulatorarm64-1.4.1-wasmjs1.klib",
          "size": 24949,
          "sha512": "89ebdbf34f0bfc27b8d2a1a5edfc4c5a70682d54bd0d6bf533b8e1716fdb3607e9a38f23cde11b8fccc7520fc72adc15064f9420885008546b5aeea639d9a34d",
          "sha256": "79d27348de580844d76f42b4031648032c275a7e38a4f9cc992cc251d822db19",
          "sha1": "d4095404885a254a63ca2c25dc44b5646b7b5dd1",
          "md5": "f6442f9f61e4a904c50837d80fb476f3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kasechange-iossimulatorarm64-1.4.1-wasmjs1-sources.jar",
          "url": "kasechange-iossimulatorarm64-1.4.1-wasmjs1-sources.jar",
          "size": 6877,
          "sha512": "79caa4e4f081c6ae2da0ec9b1a59458a1fd32ce0f20a40773c7e107228660d7fa298786d181f7a82032737c45f43cda2946810fbc583233a98402909cc63e9da",
          "sha256": "76845834bb3bd2abc37a6abeff08a32e17f76fb86cff209a883f31e6135b6324",
          "sha1": "4517cf8e34fa552f36ba5fc0e54d668f74f92ac9",
          "md5": "e82635ec1a278bfcce6d8c47ee973d92"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kasechange-iossimulatorarm64-1.4.1-wasmjs1-metadata.jar",
          "url": "kasechange-iossimulatorarm64-1.4.1-wasmjs1-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
