{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kasechange/1.4.1-wasmjs1/kasechange-1.4.1-wasmjs1.module",
    "group": "net.pearx.kasechange",
    "module": "kasechange",
    "version": "1.4.1-wasmjs1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kasechange-linuxX64Main-1.4.1-wasmjs1.klib",
          "url": "kasechange-linuxx64-1.4.1-wasmjs1.klib",
          "size": 24885,
          "sha512": "00d4b1ede7a00507bdce9d2c3f94a951e048d044dcb022b357328151ccb8124d34163c1d2dd4df59be9e74ba493ca0d25d5a2f5fbefc177dc3a7f3494551b13a",
          "sha256": "6e051efb57b28af5e502edbb05557ab03c6f541c7f9c640dbeb0ce3fdc0817c7",
          "sha1": "e5d62da5038ccc8b17f53319333c39a81a4ce981",
          "md5": "4bd60f45b3540a984974b0076c80ea7e"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kasechange-linuxx64-1.4.1-wasmjs1-sources.jar",
          "url": "kasechange-linuxx64-1.4.1-wasmjs1-sources.jar",
          "size": 6877,
          "sha512": "79caa4e4f081c6ae2da0ec9b1a59458a1fd32ce0f20a40773c7e107228660d7fa298786d181f7a82032737c45f43cda2946810fbc583233a98402909cc63e9da",
          "sha256": "76845834bb3bd2abc37a6abeff08a32e17f76fb86cff209a883f31e6135b6324",
          "sha1": "4517cf8e34fa552f36ba5fc0e54d668f74f92ac9",
          "md5": "e82635ec1a278bfcce6d8c47ee973d92"
        }
      ]
    }
  ]
}
