{
  "formatVersion": "1.1",
  "component": {
    "group": "net.pearx.kasechange",
    "module": "kasechange",
    "version": "1.4.1-wasmjs1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kasechange-metadata-1.4.1-wasmjs1.jar",
          "url": "kasechange-1.4.1-wasmjs1.jar",
          "size": 6596,
          "sha512": "3a6de60f795af81edcab93292aa6ed88f9acd6452a91acc30104e73803622e28be3df651da7528314f2079a7c5f8fb1c3a66b2d8d3be823108899ae9432b8d44",
          "sha256": "385e3222b36977b81e0561c65e9b13e829c8cf425b11068e0c943f943a30dc0d",
          "sha1": "6c9b199fb7ee6648357928636ff1d7db6c3e16b0",
          "md5": "fba3c7ab23c4cf477613e9585c53cd2a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kasechange-kotlin-1.4.1-wasmjs1-sources.jar",
          "url": "kasechange-1.4.1-wasmjs1-sources.jar",
          "size": 6877,
          "sha512": "79caa4e4f081c6ae2da0ec9b1a59458a1fd32ce0f20a40773c7e107228660d7fa298786d181f7a82032737c45f43cda2946810fbc583233a98402909cc63e9da",
          "sha256": "76845834bb3bd2abc37a6abeff08a32e17f76fb86cff209a883f31e6135b6324",
          "sha1": "4517cf8e34fa552f36ba5fc0e54d668f74f92ac9",
          "md5": "e82635ec1a278bfcce6d8c47ee973d92"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-iosarm64/1.4.1-wasmjs1/kasechange-iosarm64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-iosarm64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-iosarm64/1.4.1-wasmjs1/kasechange-iosarm64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-iosarm64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-iosarm64/1.4.1-wasmjs1/kasechange-iosarm64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-iosarm64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-iossimulatorarm64/1.4.1-wasmjs1/kasechange-iossimulatorarm64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-iossimulatorarm64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-iossimulatorarm64/1.4.1-wasmjs1/kasechange-iossimulatorarm64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-iossimulatorarm64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-iossimulatorarm64/1.4.1-wasmjs1/kasechange-iossimulatorarm64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-iossimulatorarm64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-iosx64/1.4.1-wasmjs1/kasechange-iosx64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-iosx64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-iosx64/1.4.1-wasmjs1/kasechange-iosx64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-iosx64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-iosx64/1.4.1-wasmjs1/kasechange-iosx64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-iosx64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kasechange-js/1.4.1-wasmjs1/kasechange-js-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-js",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kasechange-js/1.4.1-wasmjs1/kasechange-js-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-js",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kasechange-js/1.4.1-wasmjs1/kasechange-js-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-js",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kasechange-jvm/1.4.1-wasmjs1/kasechange-jvm-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-jvm",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kasechange-jvm/1.4.1-wasmjs1/kasechange-jvm-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-jvm",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kasechange-jvm/1.4.1-wasmjs1/kasechange-jvm-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-jvm",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-linuxx64/1.4.1-wasmjs1/kasechange-linuxx64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-linuxx64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-linuxx64/1.4.1-wasmjs1/kasechange-linuxx64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-linuxx64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-macosarm64/1.4.1-wasmjs1/kasechange-macosarm64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-macosarm64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-macosarm64/1.4.1-wasmjs1/kasechange-macosarm64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-macosarm64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-macosarm64/1.4.1-wasmjs1/kasechange-macosarm64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-macosarm64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-macosx64/1.4.1-wasmjs1/kasechange-macosx64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-macosx64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-macosx64/1.4.1-wasmjs1/kasechange-macosx64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-macosx64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-macosx64/1.4.1-wasmjs1/kasechange-macosx64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-macosx64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-mingwx64/1.4.1-wasmjs1/kasechange-mingwx64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-mingwx64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kasechange-mingwx64/1.4.1-wasmjs1/kasechange-mingwx64-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-mingwx64",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kasechange-wasm-js/1.4.1-wasmjs1/kasechange-wasm-js-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-wasm-js",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kasechange-wasm-js/1.4.1-wasmjs1/kasechange-wasm-js-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-wasm-js",
        "version": "1.4.1-wasmjs1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kasechange-wasm-js/1.4.1-wasmjs1/kasechange-wasm-js-1.4.1-wasmjs1.module",
        "group": "net.pearx.kasechange",
        "module": "kasechange-wasm-js",
        "version": "1.4.1-wasmjs1"
      }
    }
  ]
}
