{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kasechange/1.4.1-wasmjs1/kasechange-1.4.1-wasmjs1.module",
    "group": "net.pearx.kasechange",
    "module": "kasechange",
    "version": "1.4.1-wasmjs1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kasechange-jvm-1.4.1-wasmjs1.jar",
          "url": "kasechange-jvm-1.4.1-wasmjs1.jar",
          "size": 18202,
          "sha512": "31c41b8f9cceae91ff3ff9b36930133bafd176cc6e4949a9f7e55e44a7cacacd30bd591f813e6f2b96b00f259aef3c14e7a4f3658a665b35eaa8921f5f42b4a6",
          "sha256": "18366c7d3eee730b4b741c52c6fef2507f9ce08b3f630710001078c0582d1af4",
          "sha1": "d857a5f7580e55341d93779ffbe772e08b5c9f5b",
          "md5": "94317e84a925ff8a60a38773feb722d1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "kasechange-jvm-1.4.1-wasmjs1.jar",
          "url": "kasechange-jvm-1.4.1-wasmjs1.jar",
          "size": 18202,
          "sha512": "31c41b8f9cceae91ff3ff9b36930133bafd176cc6e4949a9f7e55e44a7cacacd30bd591f813e6f2b96b00f259aef3c14e7a4f3658a665b35eaa8921f5f42b4a6",
          "sha256": "18366c7d3eee730b4b741c52c6fef2507f9ce08b3f630710001078c0582d1af4",
          "sha1": "d857a5f7580e55341d93779ffbe772e08b5c9f5b",
          "md5": "94317e84a925ff8a60a38773feb722d1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kasechange-jvm-1.4.1-wasmjs1-sources.jar",
          "url": "kasechange-jvm-1.4.1-wasmjs1-sources.jar",
          "size": 6877,
          "sha512": "79caa4e4f081c6ae2da0ec9b1a59458a1fd32ce0f20a40773c7e107228660d7fa298786d181f7a82032737c45f43cda2946810fbc583233a98402909cc63e9da",
          "sha256": "76845834bb3bd2abc37a6abeff08a32e17f76fb86cff209a883f31e6135b6324",
          "sha1": "4517cf8e34fa552f36ba5fc0e54d668f74f92ac9",
          "md5": "e82635ec1a278bfcce6d8c47ee973d92"
        }
      ]
    }
  ]
}
